### ISSUE TITLE
Wrong KiKit panelize syntax in makefile

### ISSUE THREAD

**Issue by bsaid** [RoboticsBrno/RB0002-BatteryPack#10]
```
/RB0002-BatteryPack$ make
kikit panelize extractboard -s 175 50 70 40 batteryPack/batteryPack.kicad_pcb build/charger.kicad_pcb
Usage: kikit panelize [OPTIONS] INPUT OUTPUT
Try 'kikit panelize --help' for help.

Error: Got unexpected extra arguments (70 40 batteryPack/batteryPack.kicad_pcb build/charger.kicad_pcb)
make: *** [Makefile:12: build/charger.kicad_pcb] Error 2
```

Platform: Xubuntu 20.04, Python 3.8.10, KiKit version 1.0.5

Maybe the syntax changed with the new version of KiKit?
This project is mentioned as an example project inside KiKit README, so this is why I care about this issue.

**Comment by yaqwsx** [comment]
Yes, this project uses KiKit v0.4, however, there were major breaking changes in the v1.0 release.

Where did you find the mention of a Battery pack being an example? All the notes about it should be gone.

**Comment by bsaid** [comment]
[https://github.com/yaqwsx/KiKit/blob/master/README.md](https://github.com/yaqwsx/KiKit/blob/master/README.md?plain=1) line 65

**Comment by yaqwsx** [comment]
Thanks, I removed the notes. I think you might want to start with: https://github.com/yaqwsx/KiKit/blob/master/doc/examples.md

**Comment by bsaid** [comment]
I started there, but I was looking for how to make a panel from several different PCBs. Can you add this case to your examples?

**Comment by yaqwsx** [comment]
That's a duplicate of:
- https://github.com/yaqwsx/KiKit/issues/283
- https://github.com/yaqwsx/KiKit/discussions/327

Currently, this is somewhere on my Todo list, but low in priority.
