### ISSUE TITLE
Popisky +-

### ISSUE THREAD

**Issue by JakubAndrysek** [RoboticsBrno/RB0002-BatteryPack#6]
Přidat popisky i na druhou stranu desky.

**Comment by JarekParal** [comment]
Který přesně popisky myslíš ([a na které desce](https://roboticsbrno.github.io/RB0002-BatteryPack/))?
![image](https://user-images.githubusercontent.com/6726556/84593151-fb96d300-ae4a-11ea-857d-054b0b12cd12.png)

**Comment by yaqwsx** [comment]
Kuba chce velké + a velké - i na druhou stranu desky. Malé mu nestačí.

**Comment by yaqwsx** [comment]
Opraveno v 63132aa
